import Head from 'next/head'
import Sidebar from '@/components/Sidebar'
import { Container } from '@/styles/container.styled'
import {signIn, getSession, useSession, signOut} from "next-auth/react"
import { useEffect,useState } from 'react'
//import Hero from '@/components/Hero'
import Posts from './widgets/feedposts'
import Rightbar from '@/components/Rightbar'

export default function Home() {
  const [loading, setLoading] = useState(true)
  const {data: session, status} = useSession()

  useEffect(() =>{
    const securePage =async () => {
      const session = await getSession()
      if(!session){
        signIn()
      }else{
        setLoading(false)
      }
    }
    securePage()
    }, [])
    if(loading){
      return <h2> You are Logged out....</h2>
    }
  return (
    <>
      <Head>
        <title>My social App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <Container>
          <Sidebar/>
          <Posts/>
          <Rightbar/>
       </Container>
       <h1>
       {`you are signed in as ${session?.user?.name}`}
       </h1>       
       Welcome
       <button onClick={() => signOut()}>Sign out</button>
    </>
  )
}