import Head from 'next/head'
import Sidebar from '@/components/Sidebar'
import { Container } from '@/styles/container.styled'

export default function Home() {
  return (
    <>
      <Head>
        <title>My social App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <Container>
         <Sidebar/>
       </Container>
    </>
  )
}